bot:
  invest:
    isSandBoxMode: true
    token: ${secret.bot.telegram.token}
    code: TQBR

spring:
  redis:
    port: 6379
  application:
    name: stock_service


server:
  port: 8081


topic:
  share: share.topic
  bond: bond.topic
  portfolio: portfolio.topic
  request: req.topic

