bot:
  invest:
    isSandBoxMode: true
    token: ${secret.bot.invest.token}
    code: TQBR

spring:
  redis:
    port: 6379
  application:
    name: stock_service

server:
  port: 8081


topic:
  share: share.topic
  bond: bond.topic
  portfolio: portfolio.topic
  request: req.topic
  share_res: share_res.topic
  bond_res: bond_res.topic
  portfolio_res: portfolio_res.topic
