services:
  discovery:
    image: discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761
  backend:
    image: temp_app:1.0-SNAPSHOT
    ports:
      - 8080:8080
  zookeeper:
    image: 'bitnami/zookeeper:latest'

    kafka:
      image: 'bitnami/kafka:latest'

