version: "3"

services:
  discovery:
    image: discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761
  stock_service:
    image: stock_service:1.0-SNAPSHOT
    ports:
      - 8081:8080

  telegram:
    image: telegram_service:1.0-SNAPSHOT
    ports:
      - 8080:8080

  zookeeper:
    image: 'bitnami/zookeeper:latest'

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

