bot:
  telegram:
    botToken: ENC(S6KgwujnT1YaGVmbZV8w1zb9HVza/OE2HqRleKLnaE4J7FaXWHkne+bml39uoLOMWktqUhosVkY=)
    botUsername: get_my_stocks_bot
    botPath: https://dd82-78-85-4-62.ngrok.io
  invest:
    isSandBoxMode: true
    token: ENC(18NCfenZ1cvQsFhuS5ofIIAkhR4k3YgtU4Bm6HZNNJ+NIglKfuKR8pZqDLXGpOY8NIYqv1apNdW111WbWJxN2i7EzI7xdjtPaFWVTEacOVL6FVTcwma3Ul6NxMGbKY9nGLeIhZ5GRwU=)
    code: TQBR
spring:
  redis:
    port: 6379

server:
  port: 5000
