package bot.telegram.state;

public enum BotState {
    WANNA_GET_SHARE,
    SEARCH_BOND,
    SHOW_HELP_MENU,
    SHOW_START_MENU,
    MAKE_PORTFOLIO,
    UPDATE_PORTFOLIO,
    DELETE_PORTFOLIO,
    GET_PORTFOLIO,
    FIND_SHARE,
    UNRECOGNIZED
}
