server:
  port: 8080
bot:
  telegram:
    botToken: ENC(S6KgwujnT1YaGVmbZV8w1zb9HVza/OE2HqRleKLnaE4J7FaXWHkne+bml39uoLOMWktqUhosVkY=)
    botUsername: get_my_stocks_bot
    botPath: https://20de-78-85-4-62.ngrok.io
spring:
  application:
    name: telegram_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

topic:
  security: sec.topic
  request: req.topic