server:
  port: 8080
bot:
  telegram:
    botToken: ${secret.bot.telegram.token}
    botUsername: get_my_stocks_bot
    botPath: https://14e9-78-85-4-68.ngrok.io
spring:
  application:
    name: telegram_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

topic:
  portfolio: portfolio.topic
  share: share.topic
  bond: bond.topic