server:
  port: 8080
bot:
  telegram:
    botToken: ${secret.bot.telegram.token}
    botUsername: get_my_stocks_bot
    botPath: https://22c2-78-85-4-72.ngrok.io
spring:
  application:
    name: telegram_service

topic:
  portfolio: portfolio.topic
  share: share.topic
  bond: bond.topic