server:
  port: 8080
bot:
  telegram:
    botToken: ${secret.bot.telegram.token}
    botUsername: get_my_stocks_bot
    port: 8080
spring:
  application:
    name: telegram_service

topic:
  share: share.topic
  bond: bond.topic
  portfolio: portfolio.topic
  request: req.topic
  share_res: share_res.topic
  bond_res: bond_res.topic
  portfolio_res: portfolio_res.topic



logging:
  level:
    org.apache: OFF
    kafka: OFF